import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';

import { HTTP_INTERCEPTORS, provideHttpClient, withInterceptorsFromDi, withXhr } from '@angular/common/http';
import {
  provideLucideIcons,
  LucideALargeSmall,
  LucideBell,
  LucideInfo,
  LucideCircleAlert,
  LucideTriangleAlert,
  LucideArchive,
  LucideArrowDown,
  LucideArrowUp,
  LucideBinary,
  LucideBookOpen,
  LucideCalendarDays,
  LucideCircleCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronUp,
  LucideCircleQuestionMark,
  LucideClock,
  LucideCloudUpload,
  LucideCoffee,
  LucideCopy,
  LucideDatabase,
  LucideDisc,
  LucideDownload,
  LucideEllipsisVertical,
  LucideEye,
  LucideFile,
  LucideFileArchive,
  LucideFileHeadphone,
  LucideFileChartLine,
  LucideFileCheck,
  LucideFileCode,
  LucideFileCog,
  LucideFileImage,
  LucideFileBraces,
  LucideFileSpreadsheet,
  LucideFileSymlink,
  LucideFileText,
  LucideFileType,
  LucideFilePlay,
  LucideFlame,
  LucideFolder,
  LucideFolderOpen,
  LucideGlobe,
  LucideGripVertical,
  LucideHouse,
  LucideLink,
  LucideList,
  LucideLoader,
  LucideLock,
  LucideLogOut,
  LucideMoon,
  LucideSun,
  LucideHardDrive,
  LucideKeyRound,
  LucideScrollText,
  LucidePaperclip,
  LucidePencil,
  LucidePenLine,
  LucideQrCode,
  LucidePlus,
  LucideRefreshCw,
  LucideSearch,
  LucideSend,
  LucideSettings,
  LucideSquareMenu,
  LucidePlug,
  LucideTerminal,
  LucideTrash2,
  LucideWifi,
  LucideWifiOff,
  LucideX,
  LucideCircleX,
} from '@lucide/angular';
import { AuthInterceptorService } from './_services/auth/auth-interceptor.service';
import { JwtAuthProvider } from './_services/auth/providers/jwt-auth-provider.service';
import { UserPreferenceService } from './_services/user-prefrences.service';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    UserPreferenceService,
    provideLucideIcons(
      LucideBell,
      LucideInfo,
      LucideCircleAlert,
      LucideTriangleAlert,
      LucideArchive,
      LucideArrowDown,
      LucideArrowUp,
      LucideX,
      LucideSettings,
      LucideChevronDown,
      LucideChevronUp,
      LucidePencil,
      LucidePenLine,
      LucideALargeSmall,
      LucideCalendarDays,
      LucideCircleCheck,
      LucideSearch,
      LucideSend,
      LucideCircleQuestionMark,
      LucideClock,
      LucideGripVertical,
      LucideCloudUpload,
      LucideEllipsisVertical,
      LucideRefreshCw,
      LucideCopy,
      LucideDownload,
      LucidePlus,
      LucideEye,
      LucideSquareMenu,
      // Additional icons for file types
      LucideFile,
      LucideFileText,
      LucideFileImage,
      LucideFilePlay,
      LucideFileHeadphone,
      LucideFileCode,
      LucideFileCog,
      LucideFileSpreadsheet,
      LucideFileArchive,
      LucideFileChartLine,
      LucideFileCheck,
      LucideDatabase,
      LucideFolderOpen,
      LucideGlobe,
      LucideHouse,
      LucideFileBraces,
      LucideCoffee,
      LucideBinary,
      LucideFlame,
      LucideFileSymlink,
      LucideBookOpen,
      LucideTerminal,
      LucideFileType,
      LucideDisc,
      LucidePaperclip,
      LucideQrCode,
      LucideChevronRight,
      LucideFolder,
      LucideLink,
      LucideList,
      LucideLock,
      LucideLogOut,
      LucideSun,
      LucideMoon,
      LucideHardDrive,
      LucideKeyRound,
      LucideScrollText,
      LucideLoader,
      LucidePlug,
      LucideTrash2,
      LucideWifi,
      LucideWifiOff,
      LucideCircleX,
    ),
    provideHttpClient(withXhr(), withInterceptorsFromDi()),
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthInterceptorService,
      multi: true,
    },
    JwtAuthProvider,
  ],
};
