import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';

import { HTTP_INTERCEPTORS, provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import {
  ALargeSmall,
  AlertCircle,
  Binary,
  BookOpen,
  CalendarDays,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  CloudUpload,
  Coffee,
  Copy,
  Database,
  Disc,
  Download,
  EllipsisVertical,
  Eye,
  File,
  FileArchive,
  FileAudio,
  FileChartLine,
  FileCheck,
  FileCode,
  FileCog,
  FileImage,
  FileJson,
  FileSpreadsheet,
  FileSymlink,
  FileText,
  FileType,
  FileVideo,
  Flame,
  Folder,
  FolderOpen,
  Globe,
  GripVertical,
  LucideAngularModule,
  Paperclip,
  PenLine,
  Plus,
  RefreshCw,
  Send,
  Settings,
  SquareMenu,
  Terminal,
  X,
} from 'lucide-angular';
import { AuthInterceptorService } from './_services/auth/auth-interceptor.service';
import { JwtAuthProvider } from './_services/auth/providers/jwt-auth-provider.service';
import { UserPreferenceService } from './_services/user-prefrences.service';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    UserPreferenceService,
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertCircle,
        X,
        Settings,
        ChevronDown,
        ChevronUp,
        PenLine,
        ALargeSmall,
        CalendarDays,
        Send,
        CircleHelp,
        GripVertical,
        CloudUpload,
        EllipsisVertical,
        RefreshCw,
        Copy,
        Download,
        Plus,
        Eye,
        SquareMenu,
        // Additional icons for file types
        File,
        FileText,
        FileImage,
        FileVideo,
        FileAudio,
        FileCode,
        FileCog,
        FileSpreadsheet,
        FileArchive,
        FileChartLine,
        FileCheck,
        Database,
        FolderOpen,
        Globe,
        FileJson,
        Coffee,
        Binary,
        Flame,
        FileSymlink,
        BookOpen,
        Terminal,
        FileType,
        Disc,
        Paperclip,
        ChevronRight,
        Folder,
      })
    ),
    provideHttpClient(withInterceptorsFromDi()),
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthInterceptorService,
      multi: true,
    },
    JwtAuthProvider,
  ],
};
