import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';

import { HTTP_INTERCEPTORS, provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import {
  ALargeSmall,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowUp,
  Binary,
  BookOpen,
  CalendarDays,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  Clock,
  CloudUpload,
  Coffee,
  Copy,
  Database,
  Disc,
  Download,
  EllipsisVertical,
  Eye,
  File,
  FileArchive,
  FileAudio,
  FileChartLine,
  FileCheck,
  FileCode,
  FileCog,
  FileImage,
  FileJson,
  FileSpreadsheet,
  FileSymlink,
  FileText,
  FileType,
  FileVideo,
  Flame,
  Folder,
  FolderOpen,
  Globe,
  GripVertical,
  Home,
  Link,
  List,
  Loader,
  Lock,
  LogOut,
  LucideAngularModule,
  Moon,
  Sun,
  HardDrive,
  KeyRound,
  ScrollText,
  Paperclip,
  Pencil,
  PenLine,
  QrCode,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  SquareMenu,
  Plug,
  Terminal,
  Trash2,
  Wifi,
  WifiOff,
  X,
  XCircle,
} from 'lucide-angular';
import { AuthInterceptorService } from './_services/auth/auth-interceptor.service';
import { JwtAuthProvider } from './_services/auth/providers/jwt-auth-provider.service';
import { UserPreferenceService } from './_services/user-prefrences.service';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    UserPreferenceService,
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertCircle,
        AlertTriangle,
        Archive,
        ArrowDown,
  ArrowUp,
        X,
        Settings,
        ChevronDown,
        ChevronUp,
        Pencil,
        PenLine,
        ALargeSmall,
        CalendarDays,
        CheckCircle,
        Search,
        Send,
        CircleHelp,
        Clock,
        GripVertical,
        CloudUpload,
        EllipsisVertical,
        RefreshCw,
        Copy,
        Download,
        Plus,
        Eye,
        SquareMenu,
        // Additional icons for file types
        File,
        FileText,
        FileImage,
        FileVideo,
        FileAudio,
        FileCode,
        FileCog,
        FileSpreadsheet,
        FileArchive,
        FileChartLine,
        FileCheck,
        Database,
        FolderOpen,
        Globe,
        Home,
        FileJson,
        Coffee,
        Binary,
        Flame,
        FileSymlink,
        BookOpen,
        Terminal,
        FileType,
        Disc,
        Paperclip,
        QrCode,
        ChevronRight,
        Folder,
        Link,
        List,
        Lock,
        LogOut,
        Sun,
        Moon,
        HardDrive,
        KeyRound,
        ScrollText,
        Loader,
        Plug,
        Trash2,
        Wifi,
        WifiOff,
        XCircle,
      })
    ),
    provideHttpClient(withInterceptorsFromDi()),
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthInterceptorService,
      multi: true,
    },
    JwtAuthProvider,
  ],
};
